fastlane_version "1.61.0"

default_platform :ios

platform :ios do
  before_all do
    ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = '120'
    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    increment_version_number(version_number: '0.0.1')
    increment_build_number(build_number: ENV["BUILD_NUMBER"].to_s + '.0')
    update_app_identifier(plist_path: 'Info.plist',app_identifier: 'com.turner.autobuildertest')
    #sigh(skip_fetch_profiles: true)
    gym
    #pilot(skip_submission: true)
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end