fastlane_version "1.61.0"

default_platform :ios

platform :ios do
  before_all do
    ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = '120'
    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
  end
  
  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    #sigh(skip_fetch_profiles: true)
    update_app_identifier(
      xcodeproj: 'Unity-iPhone.xcodeproj',
      plist_path: "Info.plist",
      app_identifier: "com.turner.cardwars3",
    )
    gym
    #pilot(skip_submission: true)
  end
end
